trigger:
  - master

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: source-clear-credentials
  - group: android-signing
  - name: version_code
    value: $[counter('versionCode', 0)]

steps:
  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: alfresco-android-mobile-keystore
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assemblePlayStore -x verify'
    env:
      KEYSTORE_FILE: $(keystore.secureFilePath)
      KEYSTORE_PASSWORD: $(keystore_password)
      KEY_ALIAS: $(key_alias)
      KEY_PASSWORD: $(key_password)
  - bash: |
      curl -sSL https://download.sourceclear.com/ci.sh | sh
    displayName: 'SourceClearCheck'
    env:
      SRCCLR_API_TOKEN: $(source_clear_token)
  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
  - task: GooglePlayRelease@3
    inputs:
      apkFile: '**/*.apk'
      serviceEndpoint: 'Play Store Publisher'
      track: 'internal'
