trigger:
  - main

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: source-clear-credentials
  - group: android-signing
  - name: version_code
    value: $[counter('versionCode', 410)]
  - name: GRADLE_USER_HOME
    value: $(Pipeline.Workspace)/.gradle
  - name: deps_def_path
    value: buildSrc/src/main/java/com/alfresco/buildsrc/dependencies.kt
  - name: bundle_path
    value: 'app/build/outputs/bundle/playStore/*.aab'

steps:
  - task: CacheBeta@1
    inputs:
      key: 'gradle_0 | "$(Agent.OS)" | $(deps_def_path)'
      restoreKeys: gradle_0
      path: $(GRADLE_USER_HOME)
    displayName: Cache Gradle Files
  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: alfresco-android-mobile-keystore
  - task: DownloadSecureFile@1
    name: google_services
    inputs:
      secureFile: google-services-aca.json
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      options: '--no-daemon'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'bundlePlayStore'
    env:
      KEYSTORE_FILE: $(keystore.secureFilePath)
      KEYSTORE_PASSWORD: $(keystore_password)
      KEY_ALIAS: $(key_alias)
      KEY_PASSWORD: $(key_password)
      GOOGLE_SERVICES_FILE: $(google_services.secureFilePath)
  - bash: |
      curl -sSL https://download.sourceclear.com/ci.sh | sh
    displayName: 'SourceClearCheck'
    env:
      SRCCLR_API_TOKEN: $(source_clear_token)
  - task: CopyFiles@2
    inputs:
      contents: $(bundle_path)
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
  - task: GooglePlayReleaseBundle@3
    inputs:
      applicationId: 'com.alfresco.content.app'
      bundleFile: $(bundle_path)
      serviceEndpoint: 'Play Store Publisher'
      track: 'internal'
