[versions]
camera = "1.1.0-alpha04"
coil = "1.2.1"
coroutines = "1.5.0"
epoxy = "4.6.1"
exoplayer = "2.13.2"
kotlin = "1.5.0"
lifecycle = "2.3.1"
navigation = "2.3.5"
okhttp = "4.9.1"
test = "1.3.0"

[libraries]
alfresco-auth = "com.alfresco.android:auth:0.8.0-SNAPSHOT"
alfresco-content = "com.alfresco.android:content:0.3.0-SNAPSHOT"
alfresco-contentKtx = "com.alfresco.android:content-ktx:0.3.0-SNAPSHOT"

android-desugar = "com.android.tools:desugar_jdk_libs:1.0.10"
android-gradle = "com.android.tools.build:gradle:4.2.1"

androidx-activity = "androidx.activity:activity-ktx:1.2.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.0"

androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-view = "androidx.camera:camera-view:1.0.0-alpha24"

androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
androidx-core = "androidx.core:core-ktx:1.5.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.4"

androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

androidx-preference = "androidx.preference:preference:1.1.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.0"
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

androidx-test-core = { module = "androidx.test:core", version.ref = "test" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.3.0"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test" }

androidx-webkit = "androidx.webkit:webkit:1.4.0"
androidx-work = "androidx.work:work-runtime-ktx:2.5.0"

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

epoxy-core = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }

firebase-analytics = "com.google.firebase:firebase-analytics-ktx:19.0.0"
firebase-crashlytics-core = "com.google.firebase:firebase-crashlytics-ktx:18.0.0"
firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.6.1"

google-material = "com.google.android.material:material:1.3.0"

google-services-gradle = "com.google.gms:google-services:4.3.8"

gradleVersionsPlugin = "com.github.ben-manes:gradle-versions-plugin:0.38.0"

guava = "com.google.guava:guava:30.0-android"

junit = "junit:junit:4.13.2"

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"

mavericks = "com.airbnb.android:mavericks:2.2.0"

objectbox = "io.objectbox:objectbox-gradle-plugin:2.9.1"

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

photoview = "com.github.chrisbanes:PhotoView:2.3.0"

spotless = "com.diffplug.spotless:spotless-plugin-gradle:5.12.5"

subsamplingimageview = "com.davemorrissey.labs:subsampling-scale-image-view:3.10.0"
