package com.alfresco.content.mimetype

enum class MimeType(val icon: Int) {
    MS_WORD(R.drawable.file_ic_ms_word),
    MS_PPT(R.drawable.file_ic_ms_powerpoint),
    MS_EXCEL(R.drawable.file_ic_ms_excel),
    DOC_OTHER(R.drawable.file_ic_docs_other),
    PPT_OTHER(R.drawable.file_ic_presentations_other),
    SHEET_OTHER(R.drawable.file_ic_spreadsheets_other),
    DATABASE(R.drawable.file_ic_database),
    ARCHIVE(R.drawable.file_ic_archive),
    PDF(R.drawable.file_ic_pdf),
    IMAGE(R.drawable.file_ic_image_no_preview),
    VIDEO(R.drawable.file_ic_video),
    AUDIO(R.drawable.file_ic_audio),
    WEB(R.drawable.file_ic_web),
    OTHER(R.drawable.file_ic_other),
    FOLDER(R.drawable.file_ic_folder);

    companion object {
        private val map by lazy {
            mapOf(
                "application/gzip" to ARCHIVE,
                "application/json" to DOC_OTHER,
                "application/msaccess" to DATABASE,
                "application/msword" to MS_WORD,
                "application/ogg" to AUDIO,
                "application/pdf" to PDF,
                "application/postscript" to IMAGE,
                "application/rar" to ARCHIVE,
                "application/vnd.apple.keynote" to PPT_OTHER,
                "application/vnd.apple.numbers" to SHEET_OTHER,
                "application/vnd.apple.pages" to DOC_OTHER,
                "application/vnd.ms-excel" to  MS_EXCEL,
                "application/vnd.ms-powerpoint" to  MS_PPT,
                "application/vnd.oasis.opendocument.database" to DATABASE,
                "application/vnd.oasis.opendocument.graphics" to IMAGE,
                "application/vnd.oasis.opendocument.graphics-template" to IMAGE,
                "application/vnd.oasis.opendocument.image" to IMAGE,
                "application/vnd.oasis.opendocument.spreadsheet" to SHEET_OTHER,
                "application/vnd.oasis.opendocument.spreadsheet-template" to SHEET_OTHER,
                "application/vnd.oasis.opendocument.text" to DOC_OTHER,
                "application/vnd.oasis.opendocument.text-master" to DOC_OTHER,
                "application/vnd.oasis.opendocument.text-template" to DOC_OTHER,
                "application/vnd.openxmlformats-officedocument.presentationml.presentation" to  MS_PPT,
                "application/vnd.openxmlformats-officedocument.presentationml.slideshow" to  MS_PPT,
                "application/vnd.openxmlformats-officedocument.presentationml.template" to  MS_PPT,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to  MS_EXCEL,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.template" to  MS_EXCEL,
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to  MS_WORD,
                "application/vnd.openxmlformats-officedocument.wordprocessingml.template" to  MS_WORD,
                "application/vnd.stardivision.calc" to  SHEET_OTHER,
                "application/vnd.stardivision.impress" to  PPT_OTHER,
                "application/vnd.stardivision.writer" to  DOC_OTHER,
                "application/vnd.stardivision.writer-global" to  DOC_OTHER,
                "application/vnd.sun.xml.calc" to  SHEET_OTHER,
                "application/vnd.sun.xml.calc.template" to  SHEET_OTHER,
                "application/vnd.sun.xml.impress" to  PPT_OTHER,
                "application/vnd.sun.xml.impress.template" to  PPT_OTHER,
                "application/vnd.sun.xml.writer" to  DOC_OTHER,
                "application/vnd.sun.xml.writer.global" to  DOC_OTHER,
                "application/vnd.sun.xml.writer.template" to  DOC_OTHER,
                "application/x-flac" to  AUDIO,
                "application/xhtml+xml" to  WEB,
                "application/zip" to  ARCHIVE,
                "audio/3gpp" to  AUDIO,
                "audio/amr" to  AUDIO,
                "audio/basic" to  AUDIO,
                "audio/midi" to  AUDIO,
                "audio/mobile-xmf" to  AUDIO,
                "audio/midi" to AUDIO,
                "audio/mpeg" to  AUDIO,
                "audio/mpegurl" to  AUDIO,
                "audio/prs.sid" to  AUDIO,
                "audio/x-aiff" to  AUDIO,
                "audio/x-gsm" to  AUDIO,
                "audio/x-mpegurl" to  AUDIO,
                "audio/x-ms-wax" to  AUDIO,
                "audio/x-ms-wma" to  AUDIO,
                "audio/x-pn-realaudio" to  AUDIO,
                "audio/x-realaudio" to  AUDIO,
                "audio/x-scpls" to  AUDIO,
                "audio/x-sd2" to  AUDIO,
                "audio/x-wav" to  AUDIO,
                "image/bmp" to  IMAGE,
                "image/gif" to  IMAGE,
                "image/ico" to  IMAGE,
                "image/ief" to  IMAGE,
                "image/jpeg" to  IMAGE,
                "image/pcx" to  IMAGE,
                "image/png" to  IMAGE,
                "image/svg+xml" to  IMAGE,
                "image/tiff" to  IMAGE,
                "image/vnd.adobe.photoshop" to IMAGE,
                "image/vnd.djvu" to  IMAGE,
                "image/vnd.wap.wbmp" to  IMAGE,
                "image/x-cmu-raster" to  IMAGE,
                "image/x-coreldraw" to  IMAGE,
                "image/x-coreldrawpattern" to  IMAGE,
                "image/x-coreldrawtemplate" to  IMAGE,
                "image/x-corelphotopaint" to  IMAGE,
                "image/x-icon" to  IMAGE,
                "image/x-jg" to  IMAGE,
                "image/x-jng" to  IMAGE,
                "image/x-ms-bmp" to  IMAGE,
                "image/x-photoshop" to  IMAGE,
                "image/x-portable-anymap" to  IMAGE,
                "image/x-portable-bitmap" to  IMAGE,
                "image/x-portable-graymap" to  IMAGE,
                "image/x-portable-pixmap" to  IMAGE,
                "image/x-rgb" to  IMAGE,
                "image/x-xbitmap" to  IMAGE,
                "image/x-xpixmap" to  IMAGE,
                "image/x-xwindowdump" to  IMAGE,
                "text/comma-separated-values" to DOC_OTHER,
                "text/html" to  WEB,
                "text/plain" to DOC_OTHER,
                "text/richtext" to DOC_OTHER,
                "text/rtf" to DOC_OTHER,
                "text/tab-separated-values" to DOC_OTHER,
                "text/text" to DOC_OTHER,
                "text/xml" to DOC_OTHER,
                "video/3gpp" to  VIDEO,
                "video/dl" to  VIDEO,
                "video/dv" to  VIDEO,
                "video/fli" to  VIDEO,
                "video/m4v" to  VIDEO,
                "video/mp4" to  VIDEO,
                "video/mpeg" to  VIDEO,
                "video/quicktime" to  VIDEO,
                "video/vnd.mpegurl" to  VIDEO,
                "video/x-la-asf" to  VIDEO,
                "video/x-mng" to  VIDEO,
                "video/x-ms-asf" to  VIDEO,
                "video/x-ms-wm" to  VIDEO,
                "video/x-ms-wmv" to  VIDEO,
                "video/x-ms-wmx" to  VIDEO,
                "video/x-ms-wvx" to  VIDEO,
                "video/x-msvideo" to  VIDEO,
                "video/x-sgi-movie" to  VIDEO,
                "video/x-webex" to  VIDEO
            )
        }

        fun with(type: String?): MimeType {
            return map[type] ?: OTHER
        }
    }
}
