/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property type
 * @property multiValued
 * @property mandatory
 * @property displayLabel
 */
@JsonClass(generateAdapter = true)
data class ActionParameterDefinition(
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "multiValued") @field:Json(name = "multiValued") var multiValued: Boolean? = null,
    @Json(name = "mandatory") @field:Json(name = "mandatory") var mandatory: Boolean? = null,
    @Json(name = "displayLabel") @field:Json(name = "displayLabel") var displayLabel: String? = null
)
