/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * Activities describe any past activity in a site, for example creating an item of content, commenting on a node, liking an item of content.
 * @property postPersonId The id of the person who performed the activity
 * @property id The unique id of the activity
 * @property siteId The unique id of the site on which the activity was performed
 * @property postedAt The date time at which the activity was performed
 * @property feedPersonId The feed on which this activity was posted
 * @property activitySummary An object summarizing the activity
 * @property activityType The type of the activity posted
 */
@JsonClass(generateAdapter = true)
data class Activity(
    @Json(name = "postPersonId") @field:Json(name = "postPersonId") var postPersonId: String,
    @Json(name = "id") @field:Json(name = "id") var id: Long,
    @Json(name = "feedPersonId") @field:Json(name = "feedPersonId") var feedPersonId: String,
    @Json(name = "activityType") @field:Json(name = "activityType") var activityType: String,
    @Json(name = "siteId") @field:Json(name = "siteId") var siteId: String? = null,
    @Json(name = "postedAt") @field:Json(name = "postedAt") var postedAt: ZonedDateTime? = null,
    @Json(name = "activitySummary") @field:Json(name = "activitySummary") var activitySummary: Map<String, String>? = null
)
