/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id Identifier of the action definition — used for example when executing an action
 * @property name name of the action definition, e.g. \&quot;move\&quot;
 * @property title title of the action definition, e.g. \&quot;Move\&quot;
 * @property description describes the action definition, e.g. \&quot;This will move the matched item to another space.\&quot;
 * @property applicableTypes QNames of the types this action applies to
 * @property trackStatus whether the basic action definition supports action tracking or not
 * @property parameterDefinitions
 */
@JsonClass(generateAdapter = true)
data class ActionDefinition(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "applicableTypes") @field:Json(name = "applicableTypes") var applicableTypes: List<String>,
    @Json(name = "trackStatus") @field:Json(name = "trackStatus") var trackStatus: Boolean,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "parameterDefinitions") @field:Json(name = "parameterDefinitions") var parameterDefinitions: List<ActionParameterDefinition>? = null
)
