/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * @property id
 * @property auditApplicationId
 * @property createdByUser
 * @property createdAt
 * @property values
 */
@JsonClass(generateAdapter = true)
data class AuditEntry(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "auditApplicationId") @field:Json(name = "auditApplicationId") var auditApplicationId: String,
    @Json(name = "createdByUser") @field:Json(name = "createdByUser") var createdByUser: UserInfo,
    @Json(name = "createdAt") @field:Json(name = "createdAt") var createdAt: ZonedDateTime,
    @Json(name = "values") @field:Json(name = "values") var values: Map<String, Any?>? = null
)
