/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property isAdmin
 * @property isGuest
 * @property isMutable
 */
@JsonClass(generateAdapter = true)
data class Capabilities(
    @Json(name = "isAdmin") @field:Json(name = "isAdmin") var isAdmin: Boolean? = null,
    @Json(name = "isGuest") @field:Json(name = "isGuest") var isGuest: Boolean? = null,
    @Json(name = "isMutable") @field:Json(name = "isMutable") var isMutable: Boolean? = null
)
