/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * @property id
 * @property title
 * @property content
 * @property createdBy
 * @property createdAt
 * @property edited
 * @property modifiedBy
 * @property modifiedAt
 * @property canEdit
 * @property canDelete
 */
@JsonClass(generateAdapter = true)
data class Comment(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "title") @field:Json(name = "title") var title: String,
    @Json(name = "content") @field:Json(name = "content") var content: String,
    @Json(name = "createdBy") @field:Json(name = "createdBy") var createdBy: Person,
    @Json(name = "createdAt") @field:Json(name = "createdAt") var createdAt: ZonedDateTime,
    @Json(name = "edited") @field:Json(name = "edited") var edited: Boolean,
    @Json(name = "modifiedBy") @field:Json(name = "modifiedBy") var modifiedBy: Person,
    @Json(name = "modifiedAt") @field:Json(name = "modifiedAt") var modifiedAt: ZonedDateTime,
    @Json(name = "canEdit") @field:Json(name = "canEdit") var canEdit: Boolean,
    @Json(name = "canDelete") @field:Json(name = "canDelete") var canDelete: Boolean
)
