/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property organization
 * @property address1
 * @property address2
 * @property address3
 * @property postcode
 * @property telephone
 * @property fax
 * @property email
 */
@JsonClass(generateAdapter = true)
data class Company(
    @Json(name = "organization") @field:Json(name = "organization") var organization: String? = null,
    @Json(name = "address1") @field:Json(name = "address1") var address1: String? = null,
    @Json(name = "address2") @field:Json(name = "address2") var address2: String? = null,
    @Json(name = "address3") @field:Json(name = "address3") var address3: String? = null,
    @Json(name = "postcode") @field:Json(name = "postcode") var postcode: String? = null,
    @Json(name = "telephone") @field:Json(name = "telephone") var telephone: String? = null,
    @Json(name = "fax") @field:Json(name = "fax") var fax: String? = null,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null
)
