/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property type the type of the constraint
 * @property title the human-readable constraint title
 * @property description the human-readable constraint description
 * @property parameters
 */
@JsonClass(generateAdapter = true)
data class Constraint(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "parameters") @field:Json(name = "parameters") var parameters: Map<String, Map<String, Any?>>? = null
)
