/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property mimeType
 * @property mimeTypeName
 * @property sizeInBytes
 * @property encoding
 * @property mimeTypeGroup
 */
@JsonClass(generateAdapter = true)
data class ContentInfo(
    @Json(name = "mimeType") @field:Json(name = "mimeType") var mimeType: String,
    @Json(name = "mimeTypeName") @field:Json(name = "mimeTypeName") var mimeTypeName: String? = null,
    @Json(name = "sizeInBytes") @field:Json(name = "sizeInBytes") var sizeInBytes: Long? = null,
    @Json(name = "encoding") @field:Json(name = "encoding") var encoding: String? = null,
    @Json(name = "mimeTypeGroup") @field:Json(name = "mimeTypeGroup") var mimeTypeGroup: String? = null
)
