/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * @property expiresAt
 * @property validFor The length of time in seconds that the url is valid for.
 */
@JsonClass(generateAdapter = true)
data class DirectAccessUrlBodyCreate(
    @Json(name = "expiresAt") @field:Json(name = "expiresAt") var expiresAt: ZonedDateTime? = null,
    @Json(name = "validFor") @field:Json(name = "validFor") var validFor: Int? = null
)
