/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property filesAdded number of files added so far in the zip
 * @property bytesAdded number of bytes added so far in the zip
 * @property id the id of the download node
 * @property totalFiles the total number of files to be added in the zip
 * @property totalBytes the total number of bytes to be added in the zip
 * @property status the current status of the download node creation
 */
@JsonClass(generateAdapter = true)
data class Download(
    @Json(name = "filesAdded") @field:Json(name = "filesAdded") var filesAdded: Int? = null,
    @Json(name = "bytesAdded") @field:Json(name = "bytesAdded") var bytesAdded: Int? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "totalFiles") @field:Json(name = "totalFiles") var totalFiles: Int? = null,
    @Json(name = "totalBytes") @field:Json(name = "totalBytes") var totalBytes: Int? = null,
    @Json(name = "status") @field:Json(name = "status") var status: Download.StatusEnum? = null
) {
    /**
     * the current status of the download node creation
     * Values: PENDING, CANCELLED, IN_PROGRESS, DONE, MAX_CONTENT_SIZE_EXCEEDED
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "PENDING") PENDING("PENDING"),
        @Json(name = "CANCELLED") CANCELLED("CANCELLED"),
        @Json(name = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @Json(name = "DONE") DONE("DONE"),
        @Json(name = "MAX_CONTENT_SIZE_EXCEEDED") MAX_CONTENT_SIZE_EXCEEDED("MAX_CONTENT_SIZE_EXCEEDED")
    }
}
