/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property file
 * @property folder
 * @property site
 */
@JsonClass(generateAdapter = true)
data class FavoriteTarget(
    @Json(name = "file") @field:Json(name = "file") var file: FavoriteTargetNode? = null,
    @Json(name = "folder") @field:Json(name = "folder") var folder: FavoriteTargetNode? = null,
    @Json(name = "site") @field:Json(name = "site") var site: Site? = null
)
