/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * A favorite describes an Alfresco entity that a person has marked as a favorite. The target can be a site, file or folder.
 * @property targetGuid The guid of the object that is a favorite.
 * @property createdAt The time the object was made a favorite.
 * @property target
 * @property properties A subset of the target favorite properties, system properties and properties already available in the target are excluded.
 */
@JsonClass(generateAdapter = true)
data class Favorite(
    @Json(name = "targetGuid") @field:Json(name = "targetGuid") var targetGuid: String,
    @Json(name = "target") @field:Json(name = "target") var target: FavoriteTarget,
    @Json(name = "createdAt") @field:Json(name = "createdAt") var createdAt: ZonedDateTime? = null,
    @Json(name = "properties") @field:Json(name = "properties") var properties: Map<String, Any?>? = null
)
