/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Additional information of nested facet
 * @property start The start of range
 * @property startInclusive Includes values greater or equal to \&quot;start\&quot;
 * @property end The end of range
 * @property endInclusive Includes values less than or equal to \&quot;end\&quot;
 */
@JsonClass(generateAdapter = true)
data class GenericBucketBucketInfo(
    @Json(name = "start") @field:Json(name = "start") var start: String? = null,
    @Json(name = "startInclusive") @field:Json(name = "startInclusive") var startInclusive: String? = null,
    @Json(name = "end") @field:Json(name = "end") var end: String? = null,
    @Json(name = "endInclusive") @field:Json(name = "endInclusive") var endInclusive: String? = null
)
