/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Limits and usage of each quota. A network will have quotas for File space, the number of sites in the network, the number of people in the network, and the number of network administrators
 * @property id
 * @property limit
 * @property usage
 */
@JsonClass(generateAdapter = true)
data class NetworkQuota(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "limit") @field:Json(name = "limit") var limit: Long,
    @Json(name = "usage") @field:Json(name = "usage") var usage: Long
)
