/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property timeToExpire
 * @property type
 * @property lifetime
 */
@JsonClass(generateAdapter = true)
data class NodeBodyLock(
    @Json(name = "timeToExpire") @field:Json(name = "timeToExpire") var timeToExpire: Int? = null,
    @Json(name = "type") @field:Json(name = "type") var type: NodeBodyLock.TypeEnum? = null,
    @Json(name = "lifetime") @field:Json(name = "lifetime") var lifetime: NodeBodyLock.LifetimeEnum? = null
) {
    /**
     * Values: ALLOW_OWNER_CHANGES, FULL
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "ALLOW_OWNER_CHANGES") ALLOW_OWNER_CHANGES("ALLOW_OWNER_CHANGES"),
        @Json(name = "FULL") FULL("FULL")
    }
    /**
     * Values: PERSISTENT, EPHEMERAL
     */
    @JsonClass(generateAdapter = false)
    enum class LifetimeEnum(val value: String) {
        @Json(name = "PERSISTENT") PERSISTENT("PERSISTENT"),
        @Json(name = "EPHEMERAL") EPHEMERAL("EPHEMERAL")
    }
}
