/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name The name must not contain spaces or the following special characters: * \&quot; &lt; &gt; \\ / ? : and |. The character . must not be used at the end of the name.
 * @property nodeType
 * @property aspectNames
 * @property properties
 * @property permissions
 */
@JsonClass(generateAdapter = true)
data class NodeBodyUpdate(
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "nodeType") @field:Json(name = "nodeType") var nodeType: String? = null,
    @Json(name = "aspectNames") @field:Json(name = "aspectNames") var aspectNames: List<String>? = null,
    @Json(name = "properties") @field:Json(name = "properties") var properties: Map<String, String>? = null,
    @Json(name = "permissions") @field:Json(name = "permissions") var permissions: PermissionsBody? = null
)
