/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property count The number of objects in the entries array.
 * @property hasMoreItems A boolean value which is **true** if there are more entities in the collection beyond those in this response. A true value means a request with a larger value for the **skipCount** or the **maxItems** parameter will return more entities.
 * @property totalItems An integer describing the total number of entities in the collection. The API might not be able to determine this value, in which case this property will not be present.
 * @property skipCount An integer describing how many entities exist in the collection before those included in this list. If there was no **skipCount** parameter then the default value is 0.
 * @property maxItems The value of the **maxItems** parameter used to generate this list. If there was no **maxItems** parameter then the default value is 100.
 */
@JsonClass(generateAdapter = true)
data class Pagination(
    @Json(name = "count") @field:Json(name = "count") var count: Long,
    @Json(name = "hasMoreItems") @field:Json(name = "hasMoreItems") var hasMoreItems: Boolean,
    @Json(name = "skipCount") @field:Json(name = "skipCount") var skipCount: Long,
    @Json(name = "maxItems") @field:Json(name = "maxItems") var maxItems: Long,
    @Json(name = "totalItems") @field:Json(name = "totalItems") var totalItems: Long? = null
)
