/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property elements
 * @property name
 * @property isComplete
 */
@JsonClass(generateAdapter = true)
data class PathInfo(
    @Json(name = "elements") @field:Json(name = "elements") var elements: List<PathElement>? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "isComplete") @field:Json(name = "isComplete") var isComplete: Boolean? = null
)
