/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property authorityId
 * @property name
 * @property accessStatus
 */
@JsonClass(generateAdapter = true)
data class PermissionElement(
    @Json(name = "authorityId") @field:Json(name = "authorityId") var authorityId: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "accessStatus") @field:Json(name = "accessStatus") var accessStatus: PermissionElement.AccessStatusEnum? = null
) {
    /**
     * Values: ALLOWED, DENIED
     */
    @JsonClass(generateAdapter = false)
    enum class AccessStatusEnum(val value: String) {
        @Json(name = "ALLOWED") ALLOWED("ALLOWED"),
        @Json(name = "DENIED") DENIED("DENIED")
    }
}
