/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A specific preference.
 * @property id The unique id of the preference
 * @property value The value of the preference. Note that this can be of any JSON type.
 */
@JsonClass(generateAdapter = true)
data class Preference(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "value") @field:Json(name = "value") var value: String? = null
)
