/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property title the human-readable title
 * @property description the human-readable description
 * @property defaultValue the default value
 * @property dataType the name of the property type (i.g. d:text)
 * @property isMultiValued define if the property is multi-valued
 * @property isMandatory define if the property is mandatory
 * @property isMandatoryEnforced define if the presence of mandatory properties is enforced
 * @property isProtected define if the property is system maintained
 * @property constraints list of constraints defined for the property
 */
@JsonClass(generateAdapter = true)
data class Property(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "defaultValue") @field:Json(name = "defaultValue") var defaultValue: String? = null,
    @Json(name = "dataType") @field:Json(name = "dataType") var dataType: String? = null,
    @Json(name = "isMultiValued") @field:Json(name = "isMultiValued") var isMultiValued: Boolean? = null,
    @Json(name = "isMandatory") @field:Json(name = "isMandatory") var isMandatory: Boolean? = null,
    @Json(name = "isMandatoryEnforced") @field:Json(name = "isMandatoryEnforced") var isMandatoryEnforced: Boolean? = null,
    @Json(name = "isProtected") @field:Json(name = "isProtected") var isProtected: Boolean? = null,
    @Json(name = "constraints") @field:Json(name = "constraints") var constraints: List<Constraint>? = null
)
