/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id The rating scheme type. Possible values are likes and fiveStar.
 * @property myRating The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar
 */
@JsonClass(generateAdapter = true)
data class RatingBody(
    @Json(name = "id") @field:Json(name = "id") var id: RatingBody.IdEnum,
    @Json(name = "myRating") @field:Json(name = "myRating") var myRating: String
) {
    /**
     * The rating scheme type. Possible values are likes and fiveStar.
     * Values: LIKES, FIVESTAR
     */
    @JsonClass(generateAdapter = false)
    enum class IdEnum(val value: String) {
        @Json(name = "likes") LIKES("likes"),
        @Json(name = "fiveStar") FIVESTAR("fiveStar")
    }
}
