/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property numberOfRatings
 * @property average
 */
@JsonClass(generateAdapter = true)
data class RatingAggregate(
    @Json(name = "numberOfRatings") @field:Json(name = "numberOfRatings") var numberOfRatings: Int,
    @Json(name = "average") @field:Json(name = "average") var average: Int? = null
)
