/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * A person can rate an item of content by liking it. They can also remove their like of an item of content. API methods exist to get a list of ratings and to add a new rating.
 * @property id
 * @property aggregate
 * @property ratedAt
 * @property myRating The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar.
 */
@JsonClass(generateAdapter = true)
data class Rating(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "aggregate") @field:Json(name = "aggregate") var aggregate: RatingAggregate,
    @Json(name = "ratedAt") @field:Json(name = "ratedAt") var ratedAt: ZonedDateTime? = null,
    @Json(name = "myRating") @field:Json(name = "myRating") var myRating: String? = null
)
