/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property content
 * @property status
 */
@JsonClass(generateAdapter = true)
data class Rendition(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "content") @field:Json(name = "content") var content: ContentInfo? = null,
    @Json(name = "status") @field:Json(name = "status") var status: Rendition.StatusEnum? = null
) {
    /**
     * Values: CREATED, NOT_CREATED
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "CREATED") CREATED("CREATED"),
        @Json(name = "NOT_CREATED") NOT_CREATED("NOT_CREATED")
    }
}
