/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Common query defaults
 * @property textAttributes A list of query fields/properties used to expand TEXT: queries. The default is cm:content. You could include all content properties using d:content or list all individual content properties or types. As more terms are included the query size, complexity, memory impact and query time will increase.
 * @property defaultFTSOperator The default way to combine query parts when AND or OR is not explicitly stated - includes ! - + one two three (one two three)
 * @property defaultFTSFieldOperator The default way to combine query parts in field query groups when AND or OR is not explicitly stated - includes ! - + FIELD:(one two three)
 * @property namespace The default name space to use if one is not provided
 * @property defaultFieldName
 */
@JsonClass(generateAdapter = true)
data class RequestDefaults(
    @Json(name = "textAttributes") @field:Json(name = "textAttributes") var textAttributes: List<String>? = null,
    @Json(name = "defaultFTSOperator") @field:Json(name = "defaultFTSOperator") var defaultFTSOperator: RequestDefaults.DefaultFTSOperatorEnum? = null,
    @Json(name = "defaultFTSFieldOperator") @field:Json(name = "defaultFTSFieldOperator") var defaultFTSFieldOperator: RequestDefaults.DefaultFTSFieldOperatorEnum? = null,
    @Json(name = "namespace") @field:Json(name = "namespace") var namespace: String? = null,
    @Json(name = "defaultFieldName") @field:Json(name = "defaultFieldName") var defaultFieldName: String? = null
) {
    /**
     * The default way to combine query parts when AND or OR is not explicitly stated - includes ! - + one two three (one two three)
     * Values: AND, OR
     */
    @JsonClass(generateAdapter = false)
    enum class DefaultFTSOperatorEnum(val value: String) {
        @Json(name = "AND") AND("AND"),
        @Json(name = "OR") OR("OR")
    }
    /**
     * The default way to combine query parts in field query groups when AND or OR is not explicitly stated - includes ! - + FIELD:(one two three)
     * Values: AND, OR
     */
    @JsonClass(generateAdapter = false)
    enum class DefaultFTSFieldOperatorEnum(val value: String) {
        @Json(name = "AND") AND("AND"),
        @Json(name = "OR") OR("OR")
    }
}
