/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Scope
 * @property locations The locations to include in the query
 */
@JsonClass(generateAdapter = true)
data class RequestScope(
    @Json(name = "locations") @field:Json(name = "locations") var locations: RequestScope.LocationsEnum? = null
) {
    /**
     * The locations to include in the query
     * Values: NODES, VERSIONS, DELETEDMINUSNODES
     */
    @JsonClass(generateAdapter = false)
    enum class LocationsEnum(val value: String) {
        @Json(name = "nodes") NODES("nodes"),
        @Json(name = "versions") VERSIONS("versions"),
        @Json(name = "deleted-nodes") DELETEDMINUSNODES("deleted-nodes")
    }
}
