/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

/**
 * Filter Queries. Constraints that apply to the results set but do not affect the score of each entry.
 */
typealias RequestFilterQueries = List<RequestFilterQueriesInner>
