/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property maxItems The maximum number of items to return in the query results
 * @property skipCount The number of items to skip from the start of the query set
 */
@JsonClass(generateAdapter = true)
data class RequestPagination(
    @Json(name = "maxItems") @field:Json(name = "maxItems") var maxItems: Int? = null,
    @Json(name = "skipCount") @field:Json(name = "skipCount") var skipCount: Int? = null
)
