/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Limit the time and resources used for query execution
 * @property permissionEvaluationTime Maximum time for post query permission evaluation
 * @property permissionEvaluationCount Maximum count of post query permission evaluations
 */
@JsonClass(generateAdapter = true)
data class RequestLimits(
    @Json(name = "permissionEvaluationTime") @field:Json(name = "permissionEvaluationTime") var permissionEvaluationTime: Int? = null,
    @Json(name = "permissionEvaluationCount") @field:Json(name = "permissionEvaluationCount") var permissionEvaluationCount: Int? = null
)
