/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property query The filter query expression. For multi-select facets selected facets must be order together
 * @property tags Tags used exclude the filters from facet evaluation for multi-select facet support
 */
@JsonClass(generateAdapter = true)
data class RequestFilterQueriesInner(
    @Json(name = "query") @field:Json(name = "query") var query: String? = null,
    @Json(name = "tags") @field:Json(name = "tags") var tags: List<String>? = null
)
