/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property field The name of the field to highlight.
 * @property snippetCount
 * @property fragmentSize
 * @property mergeContiguous
 * @property prefix
 * @property postfix
 */
@JsonClass(generateAdapter = true)
data class RequestHighlightFields(
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "snippetCount") @field:Json(name = "snippetCount") var snippetCount: Int? = null,
    @Json(name = "fragmentSize") @field:Json(name = "fragmentSize") var fragmentSize: Int? = null,
    @Json(name = "mergeContiguous") @field:Json(name = "mergeContiguous") var mergeContiguous: Boolean? = null,
    @Json(name = "prefix") @field:Json(name = "prefix") var prefix: String? = null,
    @Json(name = "postfix") @field:Json(name = "postfix") var postfix: String? = null
)
