/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Facet range
 * @property field The name of the field to perform range
 * @property start The start of the range
 * @property end The end of the range
 * @property gap Bucket size
 * @property hardend If true means that the last bucket will end at “end” even if it is less than “gap” wide.
 * @property other before, after, between, non, all
 * @property include lower, upper, edge, outer, all
 * @property label A label to include as a pivot reference
 * @property excludeFilters Filter queries to exclude when calculating statistics
 */
@JsonClass(generateAdapter = true)
data class RequestRange(
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "start") @field:Json(name = "start") var start: String? = null,
    @Json(name = "end") @field:Json(name = "end") var end: String? = null,
    @Json(name = "gap") @field:Json(name = "gap") var gap: String? = null,
    @Json(name = "hardend") @field:Json(name = "hardend") var hardend: Boolean? = null,
    @Json(name = "other") @field:Json(name = "other") var other: List<String>? = null,
    @Json(name = "include") @field:Json(name = "include") var include: List<String>? = null,
    @Json(name = "label") @field:Json(name = "label") var label: String? = null,
    @Json(name = "excludeFilters") @field:Json(name = "excludeFilters") var excludeFilters: List<String>? = null
)
