/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

/**
 * How to sort the rows? An array of sort specifications. The array order defines the ordering precedence.
 */
typealias RequestSortDefinition = List<RequestSortDefinitionInner>
