/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request that highlight fragments to be added to result set rows The properties reflect SOLR highlighting parameters.
 * @property prefix The string used to mark the start of a highlight in a fragment.
 * @property postfix The string used to mark the end of a highlight in a fragment.
 * @property snippetCount The maximum number of distinct highlight snippets to return for each highlight field.
 * @property fragmentSize The character length of each snippet.
 * @property maxAnalyzedChars The number of characters to be considered for highlighting. Matches after this count will not be shown.
 * @property mergeContiguous If fragments over lap they can be  merged into one larger fragment
 * @property usePhraseHighlighter Should phrases be identified.
 * @property fields The fields to highlight and field specific configuration properties for each field
 */
@JsonClass(generateAdapter = true)
data class RequestHighlight(
    @Json(name = "prefix") @field:Json(name = "prefix") var prefix: String? = null,
    @Json(name = "postfix") @field:Json(name = "postfix") var postfix: String? = null,
    @Json(name = "snippetCount") @field:Json(name = "snippetCount") var snippetCount: Int? = null,
    @Json(name = "fragmentSize") @field:Json(name = "fragmentSize") var fragmentSize: Int? = null,
    @Json(name = "maxAnalyzedChars") @field:Json(name = "maxAnalyzedChars") var maxAnalyzedChars: Int? = null,
    @Json(name = "mergeContiguous") @field:Json(name = "mergeContiguous") var mergeContiguous: Boolean? = null,
    @Json(name = "usePhraseHighlighter") @field:Json(name = "usePhraseHighlighter") var usePhraseHighlighter: Boolean? = null,
    @Json(name = "fields") @field:Json(name = "fields") var fields: List<RequestHighlightFields>? = null
)
