/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A list of stats request.
 * @property field The stats field
 * @property label A label to include for reference the stats field
 * @property min The minimum value of the field
 * @property max The maximum value of the field
 * @property sum The sum of all values of the field
 * @property countValues The number which have a value for this field
 * @property missing The number which do not have a value for this field
 * @property mean The average
 * @property stddev Standard deviation
 * @property sumOfSquares Sum of all values squared
 * @property distinctValues The set of all distinct values for the field (This can be very expensive to calculate)
 * @property countDistinct The number of distinct values  (This can be very expensive to calculate)
 * @property cardinality A statistical approximation of the number of distinct values
 * @property cardinalityAccuracy Number between 0.0 and 1.0 indicating how aggressively the algorithm should try to be accurate. Used with boolean cardinality flag.
 * @property excludeFilters A list of filters to exclude
 * @property percentiles A list of percentile values, e.g. \&quot;1,99,99.9\&quot;
 */
@JsonClass(generateAdapter = true)
data class RequestStats(
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "label") @field:Json(name = "label") var label: String? = null,
    @Json(name = "min") @field:Json(name = "min") var min: Boolean? = null,
    @Json(name = "max") @field:Json(name = "max") var max: Boolean? = null,
    @Json(name = "sum") @field:Json(name = "sum") var sum: Boolean? = null,
    @Json(name = "countValues") @field:Json(name = "countValues") var countValues: Boolean? = null,
    @Json(name = "missing") @field:Json(name = "missing") var missing: Boolean? = null,
    @Json(name = "mean") @field:Json(name = "mean") var mean: Boolean? = null,
    @Json(name = "stddev") @field:Json(name = "stddev") var stddev: Boolean? = null,
    @Json(name = "sumOfSquares") @field:Json(name = "sumOfSquares") var sumOfSquares: Boolean? = null,
    @Json(name = "distinctValues") @field:Json(name = "distinctValues") var distinctValues: Boolean? = null,
    @Json(name = "countDistinct") @field:Json(name = "countDistinct") var countDistinct: Boolean? = null,
    @Json(name = "cardinality") @field:Json(name = "cardinality") var cardinality: Boolean? = null,
    @Json(name = "cardinalityAccuracy") @field:Json(name = "cardinalityAccuracy") var cardinalityAccuracy: Float? = null,
    @Json(name = "excludeFilters") @field:Json(name = "excludeFilters") var excludeFilters: List<String>? = null,
    @Json(name = "percentiles") @field:Json(name = "percentiles") var percentiles: List<Float>? = null
)
