/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Simple facet fields to include The Properties reflect the global properties related to field facts in SOLR. They are descripbed in detail by the SOLR documentation
 * @property facets Define specifc fields on which to facet (adds SOLR facet.field and f.&lt;field&gt;.facet.* options)
 */
@JsonClass(generateAdapter = true)
data class RequestFacetFields(
    @Json(name = "facets") @field:Json(name = "facets") var facets: List<RequestFacetField>? = null
)
