/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property field The field to facet on
 * @property label A label to use to identify the field facet
 * @property sets Sets the intervals for all fields.
 */
@JsonClass(generateAdapter = true)
data class RequestFacetIntervalsIntervals(
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "label") @field:Json(name = "label") var label: String? = null,
    @Json(name = "sets") @field:Json(name = "sets") var sets: List<RequestFacetSet>? = null
)
