/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name The template name
 * @property template The template
 */
@JsonClass(generateAdapter = true)
data class RequestTemplatesInner(
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "template") @field:Json(name = "template") var template: String? = null
)
