/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property query A facet query
 * @property label A label to include in place of the facet query
 */
@JsonClass(generateAdapter = true)
data class RequestFacetQueriesInner(
    @Json(name = "query") @field:Json(name = "query") var query: String? = null,
    @Json(name = "label") @field:Json(name = "label") var label: String? = null
)
