/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request that spellcheck fragments to be added to result set rows The properties reflect SOLR spellcheck parameters.
 * @property query
 */
@JsonClass(generateAdapter = true)
data class RequestSpellcheck(
    @Json(name = "query") @field:Json(name = "query") var query: String? = null
)
