/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Localization settings
 * @property timezone A valid timezone id supported by @see java.time.ZoneId
 * @property locales A list of Locales definied by IETF BCP 47.  The ordering is significant.  The first locale (leftmost) is used for sort and query localization, whereas the remaining locales are used for query only.
 */
@JsonClass(generateAdapter = true)
data class RequestLocalization(
    @Json(name = "timezone") @field:Json(name = "timezone") var timezone: String? = null,
    @Json(name = "locales") @field:Json(name = "locales") var locales: List<String>? = null
)
