/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

/**
 * Templates usewd for query expansion. A template called \"WOOF\" defined as \"%(cm:name cm:title)\" allows WOOF:example to generate cm:name:example cm:name:example
 */
typealias RequestTemplates = List<RequestTemplatesInner>
