/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type How to order - using a field, when position of the document in the index, score/relevence.
 * @property field The name of the field
 * @property ascending The sort order. (The ordering of nulls is determined by the SOLR configuration)
 */
@JsonClass(generateAdapter = true)
data class RequestSortDefinitionInner(
    @Json(name = "type") @field:Json(name = "type") var type: RequestSortDefinitionInner.TypeEnum? = null,
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "ascending") @field:Json(name = "ascending") var ascending: Boolean? = null
) {
    /**
     * How to order - using a field, when position of the document in the index, score/relevence.
     * Values: FIELD, DOCUMENT, SCORE
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "FIELD") FIELD("FIELD"),
        @Json(name = "DOCUMENT") DOCUMENT("DOCUMENT"),
        @Json(name = "SCORE") SCORE("SCORE")
    }
}
