/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The consistency state of the index used to execute the query
 * @property lastTxId The id of the last indexed transaction
 */
@JsonClass(generateAdapter = true)
data class ResponseConsistency(
    @Json(name = "lastTxId") @field:Json(name = "lastTxId") var lastTxId: Int? = null
)
