/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Context that applies to the whole result set
 * @property consistency
 * @property request
 * @property facetQueries The counts from facet queries
 * @property facetsFields The counts from field facets
 * @property facets The faceted response
 * @property spellcheck Suggested corrections  If zero results were found for the original query then a single entry of type \&quot;searchInsteadFor\&quot; will be returned. If alternatives were found that return more results than the original query they are returned as \&quot;didYouMean\&quot; options. The highest quality suggestion is first.
 */
@JsonClass(generateAdapter = true)
data class ResultSetContext(
    @Json(name = "consistency") @field:Json(name = "consistency") var consistency: ResponseConsistency? = null,
    @Json(name = "request") @field:Json(name = "request") var request: SearchRequest? = null,
    @Json(name = "facetQueries") @field:Json(name = "facetQueries") var facetQueries: List<ResultSetContextFacetQueries>? = null,
    @Json(name = "facetsFields") @field:Json(name = "facetsFields") var facetsFields: List<ResultBuckets>? = null,
    @Json(name = "facets") @field:Json(name = "facets") var facets: List<GenericFacetResponse>? = null,
    @Json(name = "spellcheck") @field:Json(name = "spellcheck") var spellcheck: List<ResultSetContextSpellcheck>? = null
)
