/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type
 * @property suggestion A suggested alternative query
 */
@JsonClass(generateAdapter = true)
data class ResultSetContextSpellcheck(
    @Json(name = "type") @field:Json(name = "type") var type: ResultSetContextSpellcheck.TypeEnum? = null,
    @Json(name = "suggestion") @field:Json(name = "suggestion") var suggestion: List<String>? = null
) {
    /**
     * Values: SEARCHINSTEADFOR, DIDYOUMEAN
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "searchInsteadFor") SEARCHINSTEADFOR("searchInsteadFor"),
        @Json(name = "didYouMean") DIDYOUMEAN("didYouMean")
    }
}
