/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property majorVersion
 * @property comment
 */
@JsonClass(generateAdapter = true)
data class RevertBody(
    @Json(name = "majorVersion") @field:Json(name = "majorVersion") var majorVersion: Boolean? = null,
    @Json(name = "comment") @field:Json(name = "comment") var comment: String? = null
)
