/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property score The score for this row
 * @property highlight Highlight fragments if requested and available. A match can happen in any of the requested field.
 */
@JsonClass(generateAdapter = true)
data class SearchEntry(
    @Json(name = "score") @field:Json(name = "score") var score: Float? = null,
    @Json(name = "highlight") @field:Json(name = "highlight") var highlight: List<SearchEntryHighlight>? = null
)
