/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property field The field where a match occured (one of the fields defined on the request)
 * @property snippets Any number of snippets for the specified field highlighting the matching text
 */
@JsonClass(generateAdapter = true)
data class SearchEntryHighlight(
    @Json(name = "field") @field:Json(name = "field") var field: String? = null,
    @Json(name = "snippets") @field:Json(name = "snippets") var snippets: List<String>? = null
)
