/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property client
 * @property message
 * @property locale
 * @property recipientEmails
 */
@JsonClass(generateAdapter = true)
data class SharedLinkBodyEmail(
    @Json(name = "client") @field:Json(name = "client") var client: String? = null,
    @Json(name = "message") @field:Json(name = "message") var message: String? = null,
    @Json(name = "locale") @field:Json(name = "locale") var locale: String? = null,
    @Json(name = "recipientEmails") @field:Json(name = "recipientEmails") var recipientEmails: List<String>? = null
)
