/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property guid
 * @property title
 * @property description
 * @property visibility
 * @property preset
 * @property role
 */
@JsonClass(generateAdapter = true)
data class Site(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "guid") @field:Json(name = "guid") var guid: String,
    @Json(name = "title") @field:Json(name = "title") var title: String,
    @Json(name = "visibility") @field:Json(name = "visibility") var visibility: Site.VisibilityEnum,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "preset") @field:Json(name = "preset") var preset: String? = null,
    @Json(name = "role") @field:Json(name = "role") var role: Site.RoleEnum? = null
) {
    /**
     * Values: PRIVATE, MODERATED, PUBLIC
     */
    @JsonClass(generateAdapter = false)
    enum class VisibilityEnum(val value: String) {
        @Json(name = "PRIVATE") PRIVATE("PRIVATE"),
        @Json(name = "MODERATED") MODERATED("MODERATED"),
        @Json(name = "PUBLIC") PUBLIC("PUBLIC")
    }
    /**
     * Values: SITECONSUMER, SITECOLLABORATOR, SITECONTRIBUTOR, SITEMANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class RoleEnum(val value: String) {
        @Json(name = "SiteConsumer") SITECONSUMER("SiteConsumer"),
        @Json(name = "SiteCollaborator") SITECOLLABORATOR("SiteCollaborator"),
        @Json(name = "SiteContributor") SITECONTRIBUTOR("SiteContributor"),
        @Json(name = "SiteManager") SITEMANAGER("SiteManager")
    }
}
