/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property message
 * @property id
 * @property title
 * @property client Optional client name used when sending an email to the end user, defaults to \&quot;share\&quot; if not provided. **Note:** The client must be registered before this API can send an email. **Note:** This is available in Alfresco 7.0.0 and newer versions.
 */
@JsonClass(generateAdapter = true)
data class SiteMembershipRequestBodyCreate(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "message") @field:Json(name = "message") var message: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "client") @field:Json(name = "client") var client: String? = null
)
