/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property title
 * @property description
 * @property visibility
 */
@JsonClass(generateAdapter = true)
data class SiteBodyCreate(
    @Json(name = "title") @field:Json(name = "title") var title: String,
    @Json(name = "visibility") @field:Json(name = "visibility") var visibility: SiteBodyCreate.VisibilityEnum,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null
) {
    /**
     * Values: PUBLIC, PRIVATE, MODERATED
     */
    @JsonClass(generateAdapter = false)
    enum class VisibilityEnum(val value: String) {
        @Json(name = "PUBLIC") PUBLIC("PUBLIC"),
        @Json(name = "PRIVATE") PRIVATE("PRIVATE"),
        @Json(name = "MODERATED") MODERATED("MODERATED")
    }
}
