/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property site
 * @property id
 * @property guid
 * @property role
 */
@JsonClass(generateAdapter = true)
data class SiteRole(
    @Json(name = "site") @field:Json(name = "site") var site: Site,
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "guid") @field:Json(name = "guid") var guid: String,
    @Json(name = "role") @field:Json(name = "role") var role: SiteRole.RoleEnum
) {
    /**
     * Values: SITECONSUMER, SITECOLLABORATOR, SITECONTRIBUTOR, SITEMANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class RoleEnum(val value: String) {
        @Json(name = "SiteConsumer") SITECONSUMER("SiteConsumer"),
        @Json(name = "SiteCollaborator") SITECOLLABORATOR("SiteCollaborator"),
        @Json(name = "SiteContributor") SITECONTRIBUTOR("SiteContributor"),
        @Json(name = "SiteManager") SITEMANAGER("SiteManager")
    }
}
