/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property person
 * @property role
 * @property isMemberOfGroup
 */
@JsonClass(generateAdapter = true)
data class SiteMember(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "person") @field:Json(name = "person") var person: Person,
    @Json(name = "role") @field:Json(name = "role") var role: SiteMember.RoleEnum,
    @Json(name = "isMemberOfGroup") @field:Json(name = "isMemberOfGroup") var isMemberOfGroup: Boolean? = null
) {
    /**
     * Values: SITECONSUMER, SITECOLLABORATOR, SITECONTRIBUTOR, SITEMANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class RoleEnum(val value: String) {
        @Json(name = "SiteConsumer") SITECONSUMER("SiteConsumer"),
        @Json(name = "SiteCollaborator") SITECOLLABORATOR("SiteCollaborator"),
        @Json(name = "SiteContributor") SITECONTRIBUTOR("SiteContributor"),
        @Json(name = "SiteManager") SITEMANAGER("SiteManager")
    }
}
