/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property role
 */
@JsonClass(generateAdapter = true)
data class SiteMembershipBodyUpdate(
    @Json(name = "role") @field:Json(name = "role") var role: SiteMembershipBodyUpdate.RoleEnum
) {
    /**
     * Values: SITECONSUMER, SITECOLLABORATOR, SITECONTRIBUTOR, SITEMANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class RoleEnum(val value: String) {
        @Json(name = "SiteConsumer") SITECONSUMER("SiteConsumer"),
        @Json(name = "SiteCollaborator") SITECOLLABORATOR("SiteCollaborator"),
        @Json(name = "SiteContributor") SITECONTRIBUTOR("SiteContributor"),
        @Json(name = "SiteManager") SITEMANAGER("SiteManager")
    }
}
