/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property userId
 */
@JsonClass(generateAdapter = true)
data class Ticket(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "userId") @field:Json(name = "userId") var userId: String? = null
)
