/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.ZonedDateTime

/**
 * @property id
 * @property versionComment
 * @property name The name must not contain spaces or the following special characters: * \&quot; &lt; &gt; \\ / ? : and |. The character . must not be used at the end of the name.
 * @property nodeType
 * @property isFolder
 * @property isFile
 * @property modifiedAt
 * @property modifiedByUser
 * @property content
 * @property aspectNames
 * @property properties
 */
@JsonClass(generateAdapter = true)
data class Version(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "nodeType") @field:Json(name = "nodeType") var nodeType: String,
    @Json(name = "isFolder") @field:Json(name = "isFolder") var isFolder: Boolean,
    @Json(name = "isFile") @field:Json(name = "isFile") var isFile: Boolean,
    @Json(name = "modifiedAt") @field:Json(name = "modifiedAt") var modifiedAt: ZonedDateTime,
    @Json(name = "modifiedByUser") @field:Json(name = "modifiedByUser") var modifiedByUser: UserInfo,
    @Json(name = "versionComment") @field:Json(name = "versionComment") var versionComment: String? = null,
    @Json(name = "content") @field:Json(name = "content") var content: ContentInfo? = null,
    @Json(name = "aspectNames") @field:Json(name = "aspectNames") var aspectNames: List<String>? = null,
    @Json(name = "properties") @field:Json(name = "properties") var properties: Map<String, Any?>? = null
)
