/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.apis

import com.alfresco.content.models.CommentBody
import com.alfresco.content.models.CommentEntry
import com.alfresco.content.models.CommentPaging
import com.alfresco.content.tools.CSV
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST
import retrofit2.http.PUT

@JvmSuppressWildcards
interface CommentsApi {
    /**
     * Create a comment
     * Creates a comment on node **nodeId**. You specify the comment in a JSON body like this:  ```JSON {   \"content\": \"This is a comment\" } ```  **Note:** You can create more than one comment by specifying a list of comments in the JSON body like this:  ```JSON [   {     \"content\": \"This is a comment\"   },   {     \"content\": \"This is another comment\"   } ] ``` If you specify a list as input, then a paginated list rather than an entry is returned in the response body. For example:  ```JSON {   \"list\": {     \"pagination\": {       \"count\": 2,       \"hasMoreItems\": false,       \"totalItems\": 2,       \"skipCount\": 0,       \"maxItems\": 100     },     \"entries\": [       {         \"entry\": {           ...         }       },       {         \"entry\": {           ...         }       }     ]   } } ```
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param commentBodyCreate The comment text. Note that you can also provide a list of comments. (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @POST("alfresco/versions/1/nodes/{nodeId}/comments")
    suspend fun createComment(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Body commentBodyCreate: CommentBody,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): CommentEntry
    /**
     * Delete a comment
     * Deletes the comment **commentId** from node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param commentId The identifier of a comment. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @DELETE("alfresco/versions/1/nodes/{nodeId}/comments/{commentId}")
    suspend fun deleteComment(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("commentId") commentId: String
    ): Unit
    /**
     * List comments
     * Gets a list of comments for the node **nodeId**, sorted chronologically with the newest comment first.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param skipCount The number of entities that exist in the collection before those included in this list. If not supplied then the default value is 0.  (optional, default to 0)
     * @param maxItems The maximum number of items to return in the list. If not supplied then the default value is 100.  (optional, default to 100)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/comments")
    suspend fun listComments(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Query("skipCount") skipCount: Int? = null,
        @retrofit2.http.Query("maxItems") maxItems: Int? = null,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): CommentPaging
    /**
     * Update a comment
     * Updates an existing comment **commentId** on node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param commentId The identifier of a comment. (required)
     * @param commentBodyUpdate The JSON representing the comment to be updated. (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @PUT("alfresco/versions/1/nodes/{nodeId}/comments/{commentId}")
    suspend fun updateComment(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("commentId") commentId: String,
        @retrofit2.http.Body commentBodyUpdate: CommentBody,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): CommentEntry
}
