/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.apis

import com.alfresco.content.models.TagBody
import com.alfresco.content.models.TagEntry
import com.alfresco.content.models.TagPaging
import com.alfresco.content.tools.CSV
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST
import retrofit2.http.PUT

@JvmSuppressWildcards
interface TagsApi {
    /**
     * Create a tag for a node
     * Creates a tag on the node **nodeId**. You specify the tag in a JSON body like this:  ```JSON {   \"tag\":\"test-tag-1\" } ```  **Note:** You can create more than one tag by specifying a list of tags in the JSON body like this:  ```JSON [   {     \"tag\":\"test-tag-1\"   },   {     \"tag\":\"test-tag-2\"   } ] ``` If you specify a list as input, then a paginated list rather than an entry is returned in the response body. For example:  ```JSON {   \"list\": {     \"pagination\": {       \"count\": 2,       \"hasMoreItems\": false,       \"totalItems\": 2,       \"skipCount\": 0,       \"maxItems\": 100     },     \"entries\": [       {         \"entry\": {           ...         }       },       {         \"entry\": {          ...         }       }     ]   } } ```
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param tagBodyCreate The new tag (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @POST("alfresco/versions/1/nodes/{nodeId}/tags")
    suspend fun createTagForNode(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Body tagBodyCreate: TagBody,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): TagEntry
    /**
     * Delete a tag from a node
     * Deletes tag **tagId** from node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param tagId The identifier of a tag. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @DELETE("alfresco/versions/1/nodes/{nodeId}/tags/{tagId}")
    suspend fun deleteTagFromNode(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("tagId") tagId: String
    ): Unit
    /**
     * Get a tag
     * Get a specific tag with **tagId**.
     * The endpoint is owned by defaultname service owner
     * @param tagId The identifier of a tag. (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/tags/{tagId}")
    suspend fun getTag(
        @retrofit2.http.Path("tagId") tagId: String,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): TagEntry
    /**
     * List tags
     * Gets a list of tags in this repository.  You can use the **include** parameter to return additional **values** information.
     * The endpoint is owned by defaultname service owner
     * @param skipCount The number of entities that exist in the collection before those included in this list. If not supplied then the default value is 0.  (optional, default to 0)
     * @param maxItems The maximum number of items to return in the list. If not supplied then the default value is 100.  (optional, default to 100)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     * @param include Returns additional information about the tag. The following optional fields can be requested: * count  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/tags")
    suspend fun listTags(
        @retrofit2.http.Query("skipCount") skipCount: Int? = null,
        @retrofit2.http.Query("maxItems") maxItems: Int? = null,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null,
        @retrofit2.http.Query("include") @CSV include: List<String>? = null
    ): TagPaging
    /**
     * List tags for a node
     * Gets a list of tags for node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param skipCount The number of entities that exist in the collection before those included in this list. If not supplied then the default value is 0.  (optional, default to 0)
     * @param maxItems The maximum number of items to return in the list. If not supplied then the default value is 100.  (optional, default to 100)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/tags")
    suspend fun listTagsForNode(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Query("skipCount") skipCount: Int? = null,
        @retrofit2.http.Query("maxItems") maxItems: Int? = null,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): TagPaging
    /**
     * Update a tag
     * Updates the tag **tagId**.
     * The endpoint is owned by defaultname service owner
     * @param tagId The identifier of a tag. (required)
     * @param tagBodyUpdate The updated tag (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @PUT("alfresco/versions/1/tags/{tagId}")
    suspend fun updateTag(
        @retrofit2.http.Path("tagId") tagId: String,
        @retrofit2.http.Body tagBodyUpdate: TagBody,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): TagEntry
}
