/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Alfresco Content Services REST API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.alfresco.content.apis

import com.alfresco.content.models.RenditionBodyCreate
import com.alfresco.content.models.RenditionEntry
import com.alfresco.content.models.RenditionPaging
import com.alfresco.content.models.RevertBody
import com.alfresco.content.models.VersionEntry
import com.alfresco.content.models.VersionPaging
import com.alfresco.content.tools.CSV
import java.time.ZonedDateTime
import okhttp3.ResponseBody
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface VersionsApi {
    /**
     * Create rendition for a file version
     * **Note:** this endpoint is available in Alfresco 7.0.0 and newer versions.  An asynchronous request to create a rendition for version of file **nodeId** and **versionId**.  The version rendition is specified by name **id** in the request body: ```JSON {   \"id\":\"doclib\" } ```   Multiple names may be specified as a comma separated list or using a list format: ```JSON [   {       \"id\": \"doclib\"   },   {       \"id\": \"avatar\"   } ] ```
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param renditionBodyCreate The rendition \&quot;id\&quot;. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @POST("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/renditions")
    suspend fun createVersionRendition(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Body renditionBodyCreate: RenditionBodyCreate
    ): Unit
    /**
     * Delete a version
     * **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Delete the version identified by **versionId** and **nodeId*.  If the version is successfully deleted then the content and metadata for that versioned node will be deleted and will no longer appear in the version history. This operation cannot be undone.  If the most recent version is deleted the live node will revert to the next most recent version.  We currently do not allow the last version to be deleted. If you wish to clear the history then you can remove the \"cm:versionable\" aspect (via update node) which will also disable versioning. In this case, you can re-enable versioning by adding back the \"cm:versionable\" aspect or using the version params (majorVersion and comment) on a subsequent file content update.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @DELETE("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}")
    suspend fun deleteVersion(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String
    ): Unit
    /**
     * Get version information
     * **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version information for **versionId** of file node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}")
    suspend fun getVersion(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String
    ): VersionEntry
    /**
     * Get version content
     * **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version content for **versionId** of file node **nodeId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response.  (optional, default to true)
     * @param ifModifiedSince Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;.  (optional)
     * @param range The Range header indicates the part of a document that the server should return. Single part request supported, for example: bytes&#x3D;1-10.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/content")
    suspend fun getVersionContent(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Query("attachment") attachment: Boolean? = null,
        @retrofit2.http.Header("If-Modified-Since") ifModifiedSince: ZonedDateTime?,
        @retrofit2.http.Header("Range") range: String?
    ): ResponseBody
    /**
     * Get rendition information for a file version
     * **Note:** this endpoint is available in Alfresco 7.0.0 and newer versions.  Gets the rendition information for **renditionId** of version of file **nodeId** and **versionId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param renditionId The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/renditions/{renditionId}")
    suspend fun getVersionRendition(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Path("renditionId") renditionId: String
    ): RenditionEntry
    /**
     * Get rendition content for a file version
     * **Note:** this endpoint is available in Alfresco 7.0.0 and newer versions.  Gets the rendition content for **renditionId** of version of file **nodeId** and **versionId**.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param renditionId The name of a thumbnail rendition, for example *doclib*, or *pdf*. (required)
     * @param attachment **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response.  (optional, default to true)
     * @param ifModifiedSince Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;.  (optional)
     * @param range The Range header indicates the part of a document that the server should return. Single part request supported, for example: bytes&#x3D;1-10.  (optional)
     * @param placeholder If **true** and there is no rendition for this **nodeId** and **renditionId**, then the placeholder image for the mime type of this rendition is returned, rather than a 404 response.  (optional, default to false)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/renditions/{renditionId}/content")
    suspend fun getVersionRenditionContent(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Path("renditionId") renditionId: String,
        @retrofit2.http.Query("attachment") attachment: Boolean? = null,
        @retrofit2.http.Header("If-Modified-Since") ifModifiedSince: ZonedDateTime?,
        @retrofit2.http.Header("Range") range: String?,
        @retrofit2.http.Query("placeholder") placeholder: Boolean? = null
    ): ResponseBody
    /**
     * List version history
     * **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version history as an ordered list of versions for the specified **nodeId**.  The list is ordered in descending modified order. So the most recent version is first and the original version is last in the list.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param include Returns additional information about the version node. The following optional fields can be requested: * properties * aspectNames  (optional)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     * @param skipCount The number of entities that exist in the collection before those included in this list. If not supplied then the default value is 0.  (optional, default to 0)
     * @param maxItems The maximum number of items to return in the list. If not supplied then the default value is 100.  (optional, default to 100)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions")
    suspend fun listVersionHistory(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Query("include") @CSV include: List<String>? = null,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null,
        @retrofit2.http.Query("skipCount") skipCount: Int? = null,
        @retrofit2.http.Query("maxItems") maxItems: Int? = null
    ): VersionPaging
    /**
     * List renditions for a file version
     * **Note:** this endpoint is available in Alfresco 7.0.0 and newer versions.  Gets a list of the rendition information for each rendition of the version of file **nodeId** and **versionId**, including the rendition id.  Each rendition returned has a **status**: CREATED means it is available to view or download, NOT_CREATED means the rendition can be requested.  You can use the **where** parameter to filter the returned renditions by **status**. For example, the following **where** clause will return just the CREATED renditions:  ``` (status='CREATED') ```
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param where A string to restrict the returned objects by using a predicate. (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/renditions")
    suspend fun listVersionRenditions(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Query("where") where: String? = null
    ): RenditionPaging
    /**
     * Revert a version
     * **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Attempts to revert the version identified by **versionId** and **nodeId** to the live node.  If the node is successfully reverted then the content and metadata for that versioned node will be promoted to the live node and a new version will appear in the version history.
     * The endpoint is owned by defaultname service owner
     * @param nodeId The identifier of a node. (required)
     * @param versionId The identifier of a version, ie. version label, within the version history of a node. (required)
     * @param revertBody Optionally, specify a version comment and whether this should be a major version, or not. (required)
     * @param fields A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @POST("alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/revert")
    suspend fun revertVersion(
        @retrofit2.http.Path("nodeId") nodeId: String,
        @retrofit2.http.Path("versionId") versionId: String,
        @retrofit2.http.Body revertBody: RevertBody,
        @retrofit2.http.Query("fields") @CSV fields: List<String>? = null
    ): VersionEntry
}
